name: Deploy

on: # トリガーの設定
  push:
    branches:
      - master # ブランチの指定

jobs:
  deploy:
    name: Deploy to server # ジョブの名前
    runs-on: ubuntu-latest # 仮想環境の指定

    steps:
      - uses: actions/checkout@v2 # チェックアウトアクション（https://github.com/actions/checkout）

      - name: Deploy files
        uses: SamKirkland/FTP-Deploy-Action@4.2.0 # FTPアップロードアクション（https://github.com/SamKirkland/FTP-Deploy-Action）
        with:
          server: ${{ secrets.PROD_SERVER }} # FTPのサーバーアドレス
          username: ${{ secrets.PROD_USERNAME }} # FTPのユーザー名
          password: ${{ secrets.PROD_PASSWORD }} # FTPのパスワード
          local-dir: ./laraproject/ # アップロードしたいファイルのパス、この場合srcディレクトリ内をアップロード対象としている
          server-dir: /public_html/laraproject/ # アップロード先のリモートパス
